<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
<h1>Adicionar nova categoria</h1>
<hr>
        <form action="salvarCategoria" method="post">
         
            <div class="mb-3">
                <label for="formGroupExampleInput2" class="form-label">Categoria</label>
                <input type="text" name="nome_categoria" class="form-control" id="formGroupExampleInput2" placeholder="categoria">
            </div>
           
        
            <div class="mb-3">
            <button type="submit" class=" form-control btn btn-primary">Salvar</button>
            </div>
            
        </form>
    </div>
    <div class="col-md-4">

    </div>
</div>