<div class="row" style="margin-top: 10px;">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
        <ol class="list-group list-group-numbered">
            <button type="button" class="btn btn-success">
                Todas as Receitas <span class="badge text-bg-dark">
                    R$: <?php
                        $totalReceita = $this->view->somaDeTodasAsReceitas['valorReceita'];
                        $totalReceita = number_format($totalReceita, 2, ',', '.');
                        echo $totalReceita;
                        ?>
                </span>
            </button>
            <?php

            date_default_timezone_set('America/Campo_Grande');
            //DATA ATUAL FROMATO PORTUGUES BRASIL
            //$DateAndTime = date('d/m/Y');
            //DATA ATUAL FORMATO AMERICANO PARA COMPRAR DATAS
            $DateAndTime = date('Y/m/d');

            foreach ($this->view->allReceitas as $despesa) {
                $data = new DateTime($despesa['data_receita']);
                $dataFormatada = $data->format('d/m/Y');
            ?>

                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold"><?= htmlentities($despesa['receita']); ?></div>
                        <?= htmlentities($despesa['descricao']); ?><br>
                        <span class="badge bg-success rounded-pill">Data da Receita <?= $dataFormatada ?></span>
                    </div>
                    <span class="badge bg-secondary rounded-pill">R$:
                        <?php
                        $despesa1 = $despesa['valor'];
                        $despesa1 = number_format($despesa1, 2, ',', '.');

                        echo htmlentities($despesa1);
                        ?>
                    </span>
                    <div class="btn-group">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">

                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">

                            <li>
                                <form action="editarReceita" method="post">
                                    <input type="hidden" name="id" value="<?= $despesa['id'] ?>">

                                    <button class="dropdown-item" type="submit">Editar</button>
                                </form>
                                <form action="excluirReceita" method="post">
                                    <input type="hidden" name="id" value="<?= $despesa['id'] ?>">

                                    <button class="dropdown-item" type="submit">Excluir</button>
                                </form>
                            </li>
                </li>
                </ul>
    </div>
    </li>
<?php } ?>

</ol>
</div>
<div class="col-md-4" style="margin-top: 10px; border: 1px solid black; overflow-x: scroll;">
    <h1 style="background-color: gray; color: white; text-align: center;">Publicidade</h1>

    <script language="JavaScript1.1" src="https://t.dynad.net/script/?dc=5550002676;ord=1677716787865;idt_product=158;aff_source=c9757d6c911e4b79bb751195a408af29;cpg=MzkyNTQ5;idt_category=862;idt_banner=3281;idt_url=392549;caf=c9757d6c911e4b79bb751195a408af29;creative=QUZJTElBRE9TX1VPTF9QbGF5X1VPTF9QbGF5XzI1MHgyNTA%3D;click="></script>

    <hr>
    <a target="_blank" href="https://www.homehost.com.br/afiliados/link.php?a=1242"><img alt="afiliado Homehost" src="https://www.homehost.com.br/afiliados/banners/63625.gif"></a>

</div>
</div>
</div>