<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
<h1>Adicionar nova Receita</h1>
<hr>
        <form action="salvarReceita" method="post">
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Valor da Receita</label>
                <input type="text" name="valor" class="form-control" id="formGroupExampleInput" placeholder="Receita em R$">
            </div>
            <div class="mb-3">
                <label for="formGroupExampleInput2" class="form-label">Descrição</label>
                <input type="text" name="descricao" class="form-control" id="formGroupExampleInput2" placeholder="descrição">
            </div>
           
            <div class="mb-3">
                <label for="formGroupExampleInput2" class="form-label">Data da receita</label>
                <input type="date" name="data_receita" class="form-control" id="formGroupExampleInput2" >
            </div>
            <div class="mb-3">
            <button type="submit" class=" form-control btn btn-primary">Salvar</button>
            </div>
            
        </form>
    </div>
    <div class="col-md-4">

    </div>
</div>