<?php
//require '/vendor/autoload.php';
?>

<div class="body_home">
    <div class="card card-campo">
        <div class="card-body">
            <b style="color: #FFD700;font-size: 1.8rem"> Inicie aqui uma jornada de administração das suas receitas e despesas mensais.</b>
            <p style="font-size: 1.5rem; color:white;"> Criar conta </p>

            <form id="cad-usuario-form">

                <span id="msgAlertErroCad"></span>
                <input type="text" name="nome" id="nome" class="form-control input-form" placeholder="Insira seu nome" value="<?= $this->view->usuario['nome'] ?>">
                <p></p>
                <input type="email" name="email" id="email" class="form-control input-form" placeholder="Entre com seu email" value="<?= $this->view->usuario['email'] ?>">
                <p></p>
                <input type="password" name="senha" class="form-control input-form" placeholder="Entre com a senha" value="<?= $this->view->usuario['senha'] ?>" id="senha">
                <p></p>

                <p></p>
                <input type="submit" class="btn btn-outline-success bt-sm botao_login" id="cad-usuario-btn" value="Cadastrar">


                <?php
                if ($this->view->erroCadastro == true) { ?>
                    <small class="form-text text-danger">*Erro ao efetuar o cadastro, verifique se todos os campos estâo
                        preenchidos
                        corretamente. Se o erro persistir, tente outro email.</small>

                <?php  }
                if ($this->view->sucessoCadastro == true) { ?>
                    <small class="form-text text-success">Cadastro realizado com sucesso,agora já pode entrar na sua conta.</small>
                <?php } ?><br>
                <a href="/login" class="text-link-cadastro" style="text-decoration: none;"> Você tem uma conta? Faça login</a>
            </form>
        </div>
    </div>
    <div class="card card-segundo-campo">
        <a href="#" style="font-size:1rem; margin-left: 5%; color: #9C9C9C; text-decoration:none;"><i class="fa-solid fa-key"></i> Esqueceu a senha ?</a>
    </div>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="js/custom.js">
    const loginForm = document.getElementById("login-usuario-form");
    const cadForm = document.getElementById("cad-usuario-form");
    const msgAlert = document.getElementById("msgAlert");
    const msgAlertErroLogin = document.getElementById("msgAlertErroLogin");
    const msgAlertErroCad = document.getElementById("msgAlertErroCad");
    const loginModal = new bootstrap.Modal(document.getElementById("loginModal"));
    //const cadModal = new bootstrap.Modal(document.getElementById("cadUsuarioModal"));

    loginForm.addEventListener("submit", async (e) => {
        e.preventDefault();

        document.getElementById("login-usuario-btn").value = "Validando...";

        if (document.getElementById("email").value === "") {
            msgAlertErroLogin.innerHTML = "<div class='alert alert-danger' role='alert'>Erro: Necessário preencher o campo usuário!</div>";
        } else if (document.getElementById("senha").value === "") {
            msgAlertErroLogin.innerHTML = "<div class='alert alert-danger' role='alert'>Erro: Necessário preencher o campo senha!</div>";
        } else {

            const dadosForm = new FormData(loginForm);

            const dados = await fetch("validar.php", {
                method: "POST",
                body: dadosForm
            });

            const resposta = await dados.json();

            if (resposta['erro']) {
                msgAlertErroLogin.innerHTML = resposta['msg']
            } else {
                document.getElementById("dados-usuario").innerHTML = "Bem vindo " + resposta['dados'].nome + "<br><a href='sair.php'>Sair</a><br>";
                loginForm.reset();
                loginModal.hide();
            }
        }

        document.getElementById("login-usuario-btn").value = "Acessar";
    });

    cadForm.addEventListener("submit", async (e) => {
        e.preventDefault();

        document.getElementById("cad-usuario-btn").value = "Salvando...";

        const dadosForm = new FormData(cadForm);

        const dados = await fetch("/registrar", {
            method: "POST",
            body: dadosForm
        });

        const resposta = await dados.json();

        console.log(resposta);

        if (resposta['erro']) {
            msgAlertErroCad.innerHTML = resposta['msg'];
        } else {
            msgAlert.innerHTML = resposta['msg'];
            cadForm.reset();
            // cadModal.hide();
        }

        document.getElementById("cad-usuario-btn").value = "Cadastrar";
    });
</script>