<?php
//require '/vendor/autoload.php';
?>

<div class="body_home">
    <div class="card card-campo">
        <div class="card-body">
            <b style="color: #FFD700;font-size: 1.8rem"> Inicie aqui uma jornada de administração das suas receitas e despesas mensais.</b>
            <p style="font-size: 1.5rem; color:white;"> Criar conta </p>

            <form id="cad-usuario-form">

                <span id="msgAlertErroCad"></span>
                <input type="text" name="nome" id="nome" class="form-control input-form" placeholder="Insira seu nome" value="<?= $this->view->usuario['nome'] ?>">
                <p></p>
                <input type="email" name="email" id="email" class="form-control input-form" placeholder="Entre com seu email" value="<?= $this->view->usuario['email'] ?>">
                <p></p>
                <input type="password" name="senha" class="form-control input-form" placeholder="Entre com a senha" value="<?= $this->view->usuario['senha'] ?>" id="senha">
                <p></p>

                <p></p>
                <input type="submit" class="btn btn-outline-success bt-sm botao_login" id="cad-usuario-btn" value="Cadastrar">


                <?php
                if ($this->view->erroCadastro == true) { ?>
                    <small class="form-text text-danger">*Erro ao efetuar o cadastro, verifique se todos os campos estâo
                        preenchidos
                        corretamente. Se o erro persistir, tente outro email.</small>

                <?php  }
                if ($this->view->sucessoCadastro == true) { ?>
                    <small class="form-text text-success">Cadastro realizado com sucesso,agora já pode entrar na sua conta.</small>
                <?php } ?><br>
                <a href="/login" class="text-link-cadastro" style="text-decoration: none;"> Você tem uma conta? Faça login</a>
            </form>
        </div>
    </div>
    <div class="card card-segundo-campo">
        <a href="#" style="font-size:1rem; margin-left: 5%; color: #9C9C9C; text-decoration:none;"><i class="fa-solid fa-key"></i> Esqueceu a senha ?</a>
    </div>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script>
    async function handleFormSubmit(event, form, msgErrorElement) {
        event.preventDefault();
    
        const submitButton = form.querySelector('input[type="submit"]');
        const originalButtonText = submitButton.value;
        submitButton.value = "Processando...";

        const formData = new FormData(form);

        try {
            const response = await fetch(form.action, {
                method: "POST",
                body: formData
            });

            if (response.ok) {
                const jsonResponse = await response.json();

                if (jsonResponse.erro) {
                    msgErrorElement.innerHTML = jsonResponse.msg;
                } else {
                    // Implementar ações após o sucesso aqui.
                    
                    form.reset();
                }
            } else {
                msgErrorElement.innerHTML = "<div class='alert alert-danger' role='alert'>Erro na requisição.</div>";
            }

        } catch (error) {
            msgErrorElement.innerHTML = "<div class='alert alert-danger' role='alert'>Erro na requisição.</div>";
        } finally {
            submitButton.value = originalButtonText;
        }
    }

    document.addEventListener("DOMContentLoaded", function() {
        const loginForm = document.getElementById("login-usuario-form");
        const cadForm = document.getElementById("cad-usuario-form");
        const msgAlertErroLogin = document.getElementById("msgAlertErroLogin");
        const msgAlertErroCad = document.getElementById("msgAlertErroCad");

        loginForm.addEventListener("submit", function(event) {
            handleFormSubmit(event, loginForm, msgAlertErroLogin);
        });

        cadForm.addEventListener("submit", function(event) {
            handleFormSubmit(event, cadForm, msgAlertErroCad);
            
        });

        document.getElementById("cad-usuario-btn").value = "Cadastrar";
    });
</script>
