<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js"></script>
    <script type="text/javascript">
        google.charts.load("current", {
            packages: ["corechart"]
        });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Categoria', 'Valor'],
                <?php foreach ($this->view->gastosPorCategorias as $categoria) {

                ?>['<?= $categoria['categoria'] ?>', <?= $categoria['total_categoria'] ?>],

                <?php } ?>
            ]);

            var options = {
                title: 'Minhas despesas Mensais',
                is3D: true,
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
            chart.draw(data, options);
        }
    </script>

</head>

<div class="row " style="margin-top: 10px;">
    <div class="col-md-4" style="margin-top: 10px;">
        <div id="piechart_3d" style="width: auto; height: auto;">
        </div>
    </div>


    <div class="col-md-4" style="margin-top: 10px;">
        <ol class="list-group list-group-numbered">
            <button type="button" class="btn btn-warning">
                <?php
                $mes = $GLOBALS;
                echo $mes['mes']; ?>Contas a vencer
                <span class="badge text-bg-dark">R$:
                    <?php

                    $contasaVencer = $this->view->Pagar['pagar'];
                    $contasaVencer = number_format($contasaVencer, 2, ',', '.');
                    echo $contasaVencer;
                    ?>
                </span>
            </button>
            <?php
            //ALERTA DE CONTA SALVA
            if (isset($_GET['msg'])) {
                $msg = $_GET['msg'];
                if ($msg == "alterado") {
            ?>
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">Muito bem!</h4>
                        <p>Conta alterada com sucesso!</p>
                        <hr>

                    </div>
                <?php } elseif ($msg == "cadastrado") { ?>
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">Muito bem!</h4>
                        <p>Conta inserida com sucesso!</p>
                        <hr>

                    </div>
            <?php  }
            }        ?>
            <?php
            $temContas = false;
            global $dataFormatada1;

            foreach ($this->view->produto as $despesa) {
                date_default_timezone_set('America/Campo_Grande');
                $mesAtual = date('m');
                $data = new DateTime($despesa['data_vencimento']);
                $dataFormatada = $data->format('d/m/Y');
                $dataFormatada1 = $data->format('m');
                $mescontas = $despesa['mes'];

                if ($despesa['mes'] = $dataFormatada1  and $despesa['status'] == 'a vencer') {
                    $temContas = true;
                    switch ($dataFormatada1) {
                        case 1:
                            echo "<div style='color: white;background-color: green; text-align:center';>Janeiro</div>";
                            break;
                        case 2:
                            echo "<div style='color: white;background-color: green; text-align:center';>Fevereiro</div>";
                            break;
                        case 3:
                            echo "<div style='color: white;background-color: green; text-align:center';>Março</div>";
                            break;
                        case 4:
                            echo "<div style='color: white;background-color: green; text-align:center';>Abril</div>";
                            break;
                        case 5:

                            echo "<div style='color: white;background-color: green; text-align:center';>Maio</div>";
                            break;
                        case 6:
                            echo "<div style='color: white;background-color: green; text-align:center';>Junho</div>";
                            break;
                        case 7:
                            echo "<div style='color: white;background-color: green; text-align:center';>Julho</div>";
                            break;
                        case 8:
                            echo "<div style='color: white;background-color: gray; text-align:center';>Agosto</div>";
                            break;
                        case 9:
                            echo "<div style='color: white;background-color: green; text-align:center';>Setembro</div>";
                            break;
                        case 10:
                            echo "<div style='color: white;background-color: green; text-align:center';>Outubro</div>";
                            break;
                        case 11:
                            echo "<div style='color: white;background-color: green; text-align:center';>Novembro</div>";
                            break;
                        case 12:
                            echo "<div style='color: white;background-color: green; text-align:center';>Dezembro</div>";
                            break;


                        default:
                            echo "<div style='color: white;background-color: green; text-align:center';>Mês não informado!</div>";
                            break;
                    }
            ?>

                    <li class="list-group-item d-flex justify-content-between align-items-start" style="margin-bottom: 10px;">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold"><?php echo htmlentities(ucwords($despesa['despesa'])); ?></div>
                            <?php echo htmlentities($despesa['descricao']); ?><br>
                            <span class="badge bg-warning rounded-pill">
                                <n>Vence em <?= $dataFormatada ?></n>
                            </span><br>

                            <span class="badge bg-info rounded-pill">
                                <n>Categoria -> <bold> <i> <?= htmlentities($despesa['categoria']); ?></i></bold>
                                </n>
                            </span>
                            <div class="col align-self-end">
                                <form action="/pagarDespesa" method="post">
                                    <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                    <input type="hidden" name="status" value="pago">

                                    <div class="d-grid gap-2">
                                        <button class="btn btn-dark">Pagar agora</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <span class="badge bg-secondary rounded-pill">R$:
                            <?php
                            $despesa1 = $despesa['valor'];
                            $despesa1 = number_format($despesa1, 2, ',', '.');
                            echo $despesa1;
                            ?>
                        </span>
                        <div class="btn-group">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">

                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <form action="editarDespesa?update=index" method="post">
                                        <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                        <input type="hidden" name="update" value="index">
                                        <button class="dropdown-item" type="submit">Editar</button>
                                    </form>
                                </li>
                                <li>
                                    <form action="excluirDespesa" method="post">
                                        <input type="hidden" name="delete" value="index">
                                        <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                        <button class="dropdown-item" type="submit">Excluir</button>
                                    </form>
                                </li>
                            </ul>
                        </div>

                    </li>

            <?php }
            }
            ?>
            <?php if ($temContas == false) { ?>
                <span class="badge bg-success rounded-pill">
                    NÃO TEM CONTAS A VENCER ESSE MÊS.
                </span>
            <?php }
            ?>

        </ol>
        <br>
        <!------->
        <ol class="list-group list-group-numbered">
            <button type="button" class="btn btn-danger">
                Contas atrasadas <span class="badge text-bg-dark"> R$:
                    <?php
                    $contasVencidas = $this->view->vencidos['vencidas'];
                    $contasVencidas = number_format($contasVencidas, 2, ',', '.');
                    echo $contasVencidas;
                    ?>
                </span>
            </button>
            <?php

            date_default_timezone_set('America/Campo_Grande');
            //DATA ATUAL FROMATO PORTUGUES BRASIL
            //$DateAndTime = date('d/m/Y');
            //DATA ATUAL FORMATO AMERICANO PARA COMPRAR DATAS
            $DateAndTime = date('Y/m/d');
            $temContasAtrasadas = false;
            foreach ($this->view->produto as $despesa) {
                date_default_timezone_set('America/Campo_Grande');
                $data = new DateTime($despesa['data_vencimento']);
                $dataFormatada = $data->format('d/m/Y');

                if ($despesa['status'] == 'atrasada' or $despesa['status'] == 'a vencer' and strtotime($despesa['data_vencimento']) < strtotime($DateAndTime)) {
                    $temContasAtrasadas = true;
                    switch ($despesa['mes']) {
                        case 1:
                            echo "<div style='color: white;background-color: green; text-align:center';>Janeiro</div>";
                            break;
                        case 2:
                            echo "<div style='color: white;background-color: green; text-align:center';>Fevereiro</div>";
                            break;
                        case 3:
                            echo "<div style='color: white;background-color: green; text-align:center';>Março</div>";
                            break;
                        case 4:
                            echo "<div style='color: white;background-color: green; text-align:center';>Abril</div>";
                            break;
                        case 5:
                            echo "<div style='color: white;background-color: green; text-align:center';>Maio</div>";
                            break;
                        case 6:
                            echo "<div style='color: white;background-color: green; text-align:center';>Junho</div>";
                            break;
                        case 7:
                            echo "<div style='color: white;background-color: green; text-align:center';>Julho</div>";
                            break;
                        case 8:
                            echo "<div style='color: white;background-color: green; text-align:center';>Agosto</div>";
                            break;
                        case 9:
                            echo "<div style='color: white;background-color: green; text-align:center';>Setembro</div>";
                            break;
                        case 10:
                            echo "<div style='color: white;background-color: green; text-align:center';>Outubro</div>";
                            break;
                        case 11:
                            echo "<div style='color: white;background-color: green; text-align:center';>Novembro</div>";
                            break;
                        case 12:
                            echo "<div style='color: white;background-color: green; text-align:center';>Dezembro</div>";
                            break;


                        default:
                            echo "<div style='color: white;background-color: green; text-align:center';>Mês não informado!</div>";
                            break;
                    }
            ?>

                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">

                            <div class="fw-bold"><?php echo htmlentities(ucwords($despesa['despesa'])); ?></div>
                            <?php echo htmlentities($despesa['descricao']); ?>
                            <span class="badge bg-danger rounded-pill">Venceu em <?= $dataFormatada ?></span>
                            <form action="/pagarDespesa" method="post">
                                <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                <input type="hidden" name="status" value="pago">
                                <button class="btn btn-info">Pagar agora</button>
                            </form>

                        </div>
                        <span class="badge bg-secondary rounded-pill">R$:
                            <?php
                            $despesa2 = $despesa['valor'];
                            $despesa2 = number_format($despesa2, 2, ',', '.');
                            echo $despesa2;
                            ?>
                        </span>

                        <div class="btn-group">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <form action="editarDespesa" method="post">
                                        <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                        <button class="dropdown-item" type="submit">Editar</button>
                                    </form>
                                </li>
                                <li>
                                    <form action="excluirDespesa" method="post">
                                        <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                        <button class="dropdown-item" type="submit">Excluir</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </li>
            <?php }
            } ?>

            <?php if ($temContasAtrasadas == false) { ?>
                <span class="badge bg-secondary rounded-pill">
                    PARABÉNS, VOCÊ ESTÁ EM DIAS COM SUAS CONTAS!
                </span>
            <?php }
            ?>
        </ol>
        <!------->
    </div>
    <div class="col-md-4" style="margin-top: 10px;  overflow-y:visible;">
        <ol class="list-group list-group-numbered">
            <button type="button" class="btn btn-success">
                Contas pagas <span class="badge text-bg-dark">R$:
                    <?php
                    $contasPagas =  $this->view->Pagos['valor'];
                    $contasPagas = number_format($contasPagas, 2, ',', '.');
                    echo $contasPagas;
                    ?>
                </span>
            </button>
            <?php

            // $DateAndTime = date('d/m/Y');
            foreach ($this->view->produto as $despesa) {
                date_default_timezone_set('America/Campo_Grande');
                // $DateAndTime = date('d/m/Y');
                $DataAtual = date('m');
                $data = new DateTime($despesa['data_pagamento']);
                $data_pagamento = $data->format('d/m/Y');
                $dataV = new DateTime($despesa['data_vencimento']);
                $data_vencimento = $dataV->format('d/m/Y');
                //  echo  "mes altual" . $DataAtual . "<br>" . "mes vindo do banco " . $despesa['mes_pagamento'] . "<br>";
                if ($despesa["status"] == "pago" and $despesa['mes_pagamento'] == $DataAtual) {
            ?>
                    <li class="list-group-item d-flex justify-content-between align-items-start" style="margin-bottom: 10px;" style="margin-bottom: 10px;">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold"><?php echo htmlentities(ucwords($despesa['despesa'])); ?></div>
                            <?php echo htmlentities($despesa['descricao']); ?><br>
                            <span class="badge bg-secondary rounded-pill">venceu em <?= $data_vencimento ?></span>
                            <span class="badge bg-success rounded-pill">Foi pago <?= $data_pagamento ?></span>
                            <form action="/naoFoiPago" method="post">
                                <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                <input type="hidden" name="status" value="a vencer">
                                <button class="btn btn-warning">Não foi pago</button>
                            </form>
                        </div>
                        <span class="badge bg-primary rounded-pill">R$:
                            <?php
                            $despesa3 = $despesa['valor'];
                            $despesa3 = number_format($despesa3, 2, ',', '.');

                            echo $despesa3;
                            ?>
                        </span>

                        <div class="btn-group">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">

                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <form action="editarDespesa" method="post">
                                        <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                        <button class="dropdown-item" type="submit">Editar</button>
                                    </form>
                                </li>
                                <li>
                                    <form action="excluirDespesa" method="post">
                                        <input type="hidden" name="id" value="<?= $despesa['id'] ?>">
                                        <button class="dropdown-item" type="submit">Excluir</button>
                                    </form>
                                </li>
                            </ul>
                        </div>

                    </li>

            <?php }
            } ?>
        </ol>
        <!--
        <h1 style="background-color: gray; color: white; text-align: center;">Publicidade</h1>

        <script language="JavaScript1.1" src="https://t.dynad.net/script/?dc=5550002676;ord=1677716787865;idt_product=158;aff_source=c9757d6c911e4b79bb751195a408af29;cpg=MzkyNTQ5;idt_category=862;idt_banner=3281;idt_url=392549;caf=c9757d6c911e4b79bb751195a408af29;creative=QUZJTElBRE9TX1VPTF9QbGF5X1VPTF9QbGF5XzI1MHgyNTA%3D;click="></script>
        <hr>

        <a target="_blank" href="https://www.homehost.com.br/afiliados/link.php?a=1242"><img alt="afiliado Homehost" src="https://www.homehost.com.br/afiliados/banners/63625.gif"></a>
-->

    </div>
</div>