<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WS - Controle Financeiro</title>

    <link rel="shortcut icon" href="imagens/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="css/style.css">

</head>

<body>
    <div class="">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">WS - Controle Financeiro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                / Adicionar
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/despesa">Despesa</a></li>
                                <li><a class="dropdown-item" href="/receita">Receita</a></li>

                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contasPagas">/ Contas Pagas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/sair">/ Sair</a>
                        </li>
                    </ul>
                    <a class="nav-link" href="/perfil"><strong><?php echo htmlentities(ucwords($_SESSION['nome'])); ?></strong></a>
                    <!--  <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>-->
                </div>
            </div>

        </nav>

        <div style="border-bottom: 10px; background-color:darkgrey;" class="row">
            <div class="col-md-3">
                <!-- BOTÃO DE SALDO PREVISTO-->
                <div class="btn btn-warning" id="botoeSaldo">
                    Saldo Previsto
                    <span class="badge text-bg-secondary">R$:
                        <?php
                        $total = $this->view->todasAsReceitas['valorReceita'] - $this->view->todasAsDespesas['allDespesas'];
                        $total = number_format($total, 2, ',', '.'); // R$100.000,50

                        echo $total;
                        ?>
                    </span>
                    <hr>

                    Saldo Real <span class="badge text-bg-secondary">R$:
                        <?php
                        $total = $this->view->todasAsReceitas['valorReceita'] - $this->view->Pagos['valor'];
                        $total = number_format($total, 2, ',', '.'); // R$100.000,50

                        echo $total;
                        ?>
                    </span>
                </div>

            </div>
            <div class="col-md-3">

                <a href="/receitas">
                    <div class="btn btn-success" id="botoeReceitaDespesa">
                        Receitas
                        <span class="badge text-bg-secondary">R$:
                            <?php
                            $receita = $this->view->todasAsReceitas['valorReceita'];
                            $receita = number_format($receita, 2, ',', '.'); // R$100.000,50 
                            echo $receita;
                            ?>
                        </span>
                    </div>
                </a>

                <a href="/despesas">
                    <div class="btn btn-danger" id="botoeReceitaDespesa">
                        Despesas
                        <span class="badge text-bg-secondary" title="Despesa">R$:
                            <?php
                            $despesa = $this->view->todasAsDespesas['allDespesas'];
                            $despesa = number_format($despesa, 2, ',', '.'); // R$100.000,50
                            echo $despesa;
                            ?>
                        </span>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <!-- Button trigger modal Adiconar nova Despesa-->
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                    </svg>
                </button>

                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="staticBackdropLabel">Adicionar nova despesa</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">

                                <form action="salvarDespesa" method="post">
                                    <?php
                                    if ($this->view->erroProduto) { ?>
                                        <small class="form-text text-danger">*Erro ao adicionar nova despesa, verifique se todos os campos estão prenchidos corretamente.</small>

                                    <?php  } ?>
                                    <div class="mb-3">
                                        <label for="formGroupExampleInput" class="form-label">Descrição</label>
                                        <input type="text" name="despesa" class="form-control" id="formGroupExampleInput" placeholder="descrição" value="<?= $this->view->produto['despesa'] ?>" required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="formGroupExampleInput2" class="form-label">Complemento</label>
                                        <input type="text" name="descricao" class="form-control" id="formGroupExampleInput2" placeholder="informações complementares" value="<?= $this->view->produto['descricao'] ?>">
                                    </div>
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label for="formGroupExampleInput2" class="form-label">Valor</label>
                                                <input type="text" name="valor" class="form-control" id="formGroupExampleInput2" placeholder="R$" value="<?= $this->view->produto['valor'] ?>" required>
                                            </div>
                                            <div class="col-md-6">
                                                <label for="formGroupExampleInput3" class="form-label">Já foi pago?</label><br>Sim
                                                <input type="checkbox" name="status" value="pago" id="formGroupExampleInput3">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <label for="r" class="form-label" style="color: black;">Repetir despesa</label>
                                        <input type="checkbox" name="repetir" id="r" placeholder="informações complementares" value="<?= $this->view->produto['descricao'] ?>">
                                    </div>

                                    <div class="mb-3">
                                        <label for="formGroupExampleInput2" class="form-label">Categoria</label>
                                        <select name="categoria" id="formGroupExampleInput2" class="form-control">
                                            <option value="<?= $this->view->produto['categoria'] ?>">Selecionar Categoria</option>
                                            <?php foreach ($this->view->categorias as $categoria) {
                                                if ($categoria['id_usuario'] == 0 or $categoria['id_usuario'] == $_SESSION['id']) {

                                            ?>
                                                    <option value="<?= $categoria['nome_categoria'] ?>">
                                                        <?= $categoria['nome_categoria'] ?>
                                                    </option>

                                            <?php }
                                            } ?>

                                        </select>
                                        <label for="formGroupExampleInput3" class="form-label" style="color: red;">Não tem a categoria que procura? </label>
                                        <a href="/novaCategoria" style="text-decoration: none;">Criar nova categoria</a>

                                    </div>

                                    <div class="mb-3">
                                        <label for="formGroupExampleInput2" class="form-label">Data de vencimento</label>
                                        <input type="date" name="data_vencimento" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder" value="<?= $this->view->produto['data_venciemnto'] ?>" required>
                                    </div>


                            </div>
                            <div class="modal-footer">
                                <button type="cancel" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Salvar</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Button trigger modal Nova Receita -->
                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                    </svg>
                </button>

                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="staticBackdropLabel">Adicionar nova Receita</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">

                                <form action="salvarReceita" method="post">
                                    <div class="mb-3">
                                        <label for="formGroupExampleInput" class="form-label">Valor da Receita</label>
                                        <input type="number" name="valor" class="form-control" id="formGroupExampleInput" placeholder="Receita em R$">
                                    </div>
                                    <div class="mb-3">
                                        <label for="formGroupExampleInput2" class="form-label">Descrição</label>
                                        <input type="text" name="descricao" class="form-control" id="formGroupExampleInput2" placeholder="descrição">
                                    </div>
                                    <div class="mb-3">
                                        <label for="formGroupExampleInput2" class="form-label">Data da receita</label>
                                        <input type="date" name="data_receita" class="form-control" id="formGroupExampleInput2">
                                    </div>

                            </div>
                            <div class="modal-footer">
                                <button type="cancel" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Salvar</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="col-md-3">
                <form action="/">
                    <div class="row">
                        <div class="col-md-10">
                            <select class="form-select" id="data" aria-label="Default select example" name="data_vencimento">
                                <option selected>Buscar despesas pelo mês.</option>
                                <option value="01" data-url="/?data_vencimento=01">Janeiro</option>
                                <option value="02" data-url="/?data_vencimento=02">Fevereiro</option>
                                <option value="03" data-url="/?data_vencimento=03">Março</option>
                                <option value="04" data-url="/?data_vencimento=04">Abril</option>
                                <option value="05" data-url="/?data_vencimento=05">Maio</option>
                                <option value="06" data-url="/?data_vencimento=06">Junho</option>
                                <option value="07" data-url="/?data_vencimento=07">Julho</option>
                                <option value="08" data-url="/?data_vencimento=08">Agosto</option>
                                <option value="09" data-url="/?data_vencimento=09">Setembro</option>
                                <option value="10" data-url="/?data_vencimento=10">Outubro</option>
                                <option value="11" data-url="/?data_vencimento=11">Novembro</option>
                                <option value="12" data-url="/?data_vencimento=12">Dezembro</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary">Buscar</button>
                        </div>
                    </div>

                </form>
                <script>
                    /* var select = document.querySelector('#data');
                    select.addEventListener('change', function() {
                        var selecionada = this.options[this.selectedIndex];
                        var url = selecionada.getAttribute('data-url');
                        if (url) window.location = url;
                    });*/
                </script>
            </div>
        </div>
        <div style=" background-color: grey;">
            <?= $this->content() ?>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="js/custom.js"></script>
</body>

</html>